FROM envoyproxy/envoy:v1.11.2

RUN apt-get update && \
    apt-get install -y jq gettext curl

COPY edge_config/docker-entrypoint.sh /

RUN chmod 500 /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]